CREATE DATABASE IF NOT EXISTS import_csv;

-- id;name;slug;uic;uic8_sncf;latitude;longitude;parent_station_id;country;time_zone;is_city;is_main_station;is_airport;is_suggestable;country_hint;main_station_hint;sncf_id;sncf_tvs_id;sncf_is_enabled;entur_id;entur_is_enabled;db_id;db_is_enabled;busbud_id;busbud_is_enabled;distribusion_id;distribusion_is_enabled;flixbus_id;flixbus_is_enabled;cff_id;cff_is_enabled;leoexpress_id;leoexpress_is_enabled;obb_id;obb_is_enabled;ouigo_id;ouigo_is_enabled;trenitalia_id;trenitalia_is_enabled;trenitalia_rtvt_id;trenord_id;ntv_rtiv_id;ntv_id;ntv_is_enabled;hkx_id;hkx_is_enabled;renfe_id;renfe_is_enabled;atoc_id;atoc_is_enabled;benerail_id;benerail_is_enabled;westbahn_id;westbahn_is_enabled;sncf_self_service_machine;same_as;info:de;info:en;info:es;info:fr;info:it;info:nb;info:nl;info:cs;info:da;info:hu;info:ja;info:ko;info:pl;info:pt;info:ru;info:sv;info:tr;info:zh;normalised_code;iata_airport_code

USE import_csv;

DROP TABLE IF EXISTS stations;

CREATE TABLE stations (
    id INT UNSIGNED NOT NULL,
    name VARCHAR(150) NULL,
    slug VARCHAR(150) NULL,
    uic VARCHAR(50) NULL,
    uic8_sncf VARCHAR(50) NULL,
    latitude VARCHAR(50) NULL,
    longitude VARCHAR(50) NULL,
    parent_station_id VARCHAR(50) NULL,
    country VARCHAR(50) NULL,
    time_zone VARCHAR(50) NULL,
    is_city VARCHAR(50) NULL,
    is_main_station VARCHAR(50) NULL,
    is_airport VARCHAR(50) NULL,
    is_suggestable VARCHAR(50) NULL,
    country_hint VARCHAR(50) NULL,
    main_station_hint VARCHAR(50) NULL,
    sncf_id VARCHAR(50) NULL,
    sncf_tvs_id VARCHAR(50) NULL,
    sncf_is_enabled VARCHAR(50) NULL,
    entur_id VARCHAR(50) NULL,
    entur_is_enabled VARCHAR(50) NULL,
    db_id VARCHAR(50) NULL,
    db_is_enabled VARCHAR(50) NULL,
    busbud_id VARCHAR(50) NULL,
    busbud_is_enabled VARCHAR(50) NULL,
    distribusion_id VARCHAR(50) NULL,
    distribusion_is_enabled VARCHAR(50) NULL,
    flixbus_id VARCHAR(50) NULL,
    flixbus_is_enabled VARCHAR(50) NULL,
    cff_id VARCHAR(50) NULL,
    cff_is_enabled VARCHAR(50) NULL,
    leoexpress_id VARCHAR(50) NULL,
    leoexpress_is_enabled VARCHAR(50) NULL,
    obb_id VARCHAR(50) NULL,
    obb_is_enabled VARCHAR(50) NULL,
    ouigo_id VARCHAR(50) NULL,
    ouigo_is_enabled VARCHAR(50) NULL,
    trenitalia_id VARCHAR(50) NULL,
    trenitalia_is_enabled VARCHAR(50) NULL,
    trenitalia_rtvt_id VARCHAR(50) NULL,
    trenord_id VARCHAR(50) NULL,
    ntv_rtiv_id VARCHAR(50) NULL,
    ntv_id VARCHAR(50) NULL,
    ntv_is_enabled VARCHAR(50) NULL,
    hkx_id VARCHAR(50) NULL,
    hkx_is_enabled VARCHAR(50) NULL,
    renfe_id VARCHAR(50) NULL,
    renfe_is_enabled VARCHAR(50) NULL,
    atoc_id VARCHAR(50) NULL,
    atoc_is_enabled VARCHAR(50) NULL,
    benerail_id VARCHAR(50) NULL,
    benerail_is_enabled VARCHAR(50) NULL,
    westbahn_id VARCHAR(50) NULL,
    westbahn_is_enabled VARCHAR(50) NULL,
    sncf_self_service_machine VARCHAR(50) NULL,
    same_as VARCHAR(50) NULL,
    `info:de` VARCHAR(50) NULL,
    `info:en` VARCHAR(50) NULL,
    `info:es` VARCHAR(50) NULL,
    `info:fr` VARCHAR(50) NULL,
    `info:it` VARCHAR(50) NULL,
    `info:nb` VARCHAR(50) NULL,
    `info:nl` VARCHAR(50) NULL,
    `info:cs` VARCHAR(50) NULL,
    `info:da` VARCHAR(50) NULL,
    `info:hu` VARCHAR(50) NULL,
    `info:ja` VARCHAR(50) NULL,
    `info:ko` VARCHAR(50) NULL,
    `info:pl` VARCHAR(50) NULL,
    `info:pt` VARCHAR(50) NULL,
    `info:ru` VARCHAR(50) NULL,
    `info:sv` VARCHAR(50) NULL,
    `info:tr` VARCHAR(50) NULL,
    `info:zh` VARCHAR(50) NULL,
    normalised_code VARCHAR(50) NULL,
    iata_airport_code CHAR(3) NULL,
    PRIMARY KEY (id)
);

LOAD DATA INFILE 'C:\\projects\\load-data-mysql-exercise\\stations.csv'
INTO TABLE stations
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(
    id, 
    name,
    slug,
    uic,
    uic8_sncf,
    latitude,
    longitude,
    parent_station_id,
    country,
    time_zone,
    is_city,
    is_main_station,
    is_airport,
    is_suggestable,
    country_hint,
    main_station_hint,
    sncf_id,
    sncf_tvs_id,
    sncf_is_enabled,
    entur_id,
    entur_is_enabled,
    db_id,
    db_is_enabled,
    busbud_id,
    busbud_is_enabled,
    distribusion_id,
    distribusion_is_enabled,
    flixbus_id,
    flixbus_is_enabled,
    cff_id,
    cff_is_enabled,
    leoexpress_id,
    leoexpress_is_enabled,
    obb_id,
    obb_is_enabled,
    ouigo_id,
    ouigo_is_enabled,
    trenitalia_id,
    trenitalia_is_enabled,
    trenitalia_rtvt_id,
    trenord_id,
    ntv_rtiv_id,
    ntv_id,
    ntv_is_enabled,
    hkx_id,
    hkx_is_enabled,
    renfe_id,
    renfe_is_enabled,
    atoc_id,
    atoc_is_enabled,
    benerail_id,
    benerail_is_enabled,
    westbahn_id,
    westbahn_is_enabled,
    sncf_self_service_machine,
    same_as,
    `info:de`,
    `info:en`,
    `info:es`,
    `info:fr`,
    `info:it`,
    `info:nb`,
    `info:nl`,
    `info:cs`,
    `info:da`,
    `info:hu`,
    `info:ja`,
    `info:ko`,
    `info:pl`,
    `info:pt`,
    `info:ru`,
    `info:sv`,
    `info:tr`,
    `info:zh`,
    normalised_code,
    @iata_airport_code
)
SET iata_airport_code = NULLIF( IFNULL(@iata_airport_code, ''),'' );

SELECT id,name, `info:it`, iata_airport_code, normalised_code
FROM stations
WHERE iata_airport_code IS NOT NULL
  AND country = 'IT';
